### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by kelunik** [nikic/PHP-Fuzzer#13]
Hey @nikic, could you please tag a new version with a new PHAR? The current release is broken due to https://github.com/nikic/PHP-Fuzzer/commit/3d8718ac1ca7cac185a27b1eb6fcb6ac28dc8c37.

**Comment by nikic** [comment]
Done! https://github.com/nikic/PHP-Fuzzer/releases/tag/v0.0.8

**Comment by kelunik** [comment]
Thanks!
