### ISSUE TITLE
Windows is not supported due to pcntl

### ISSUE THREAD

**Issue by xPaw** [nikic/PHP-Fuzzer#2]
If it can't be supported, this could be mentioned in the readme.

```
PHP Fatal error:  Uncaught Error: Call to undefined function pcntl_signal() in phar://php-fuzzer.phar/src/Fuzzer.php:415
```

**Comment by nikic** [comment]
pcntl is only used for the timeout functionality, so it can be easily made optional. I forgot this isn't available on Windows.

**Comment by nikic** [comment]
I've create a new release that should hopefully be compatible with Windows: https://github.com/nikic/PHP-Fuzzer/releases/tag/v0.0.4
