### ISSUE TITLE
[Idea] Configure the whitelisted exception base class

### ISSUE THREAD

**Issue by stof** [nikic/PHP-Fuzzer#6]
Currently, the fuzzer accepts any `Exception` being thrown. However, for parsing libraries, it is common to define a contract about throwing a particular kind of exception (for instance, in `scssphp/scssphp`, we say that any failure will be reported by an exception implement `ScssPhp\ScssPhp\Exception\SassException`).
It would be great to be able to configure this, so that any `Exception` throw that is not a subtype of the whitelisted exception type would also be considered as a bug in the library. Note that this needs supporting passing an interface as the whitelist, not only the name of a class exending `\Exception` (Our `SassException` is actually an interface implemented by our internal exception classes).

**Comment by nikic** [comment]
A workaround would be to manually change other exceptions into Error:

```
try {
    /* ... */
} catch (SassException $e) {
    /* ignore -- this is expected! */
} catch (Throwable $e) {
    throw new Error("An exception was thrown", 0, $e);
}
```

**Comment by stof** [comment]
indeed, this works today as a workaround.
It might still be a good idea to make it simpler.

**Comment by stof** [comment]
small improvement over your proposal, for anyone reading this: the second catch should catch only `\Exception` rather than `\Throwable`, to avoid wrapping Errors into another Error. This makes their stack trace easier to read.
